### ISSUE TITLE
qbittorrent 容器重启后所有已经下载好的种子全部又会重新开始下载

### ISSUE THREAD

**Issue by fillpit** [firemakergk/aquar-build-helper#18]
![image](https://github.com/firemakergk/aquar-build-helper/assets/90119466/89329228-d817-4468-a154-13afff059ceb)
下面是 容器日志
[logs.log](https://github.com/firemakergk/aquar-build-helper/files/12156865/logs.log)

```
version: '3.1'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    networks:
      br0:
        ipv4_address: 10.0.0.34
    dns:
      - 10.0.0.1
      - 223.5.5.5
    dns_search:
      - local
    volumes:
      - /mnt/user/Downloads/:/downloads:rw
      - /mnt/user/Media/:/media:rw
      - /mnt/user/appdata/qbittorrent/data:/config:rw
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Shanghai

networks:
  br0:
    external: true
    name: br0

```
这是容器的配置

我没有用你提供的脚本,而是根据你的思路来设置的, 能解答一下吗?非常感谢
